# -*- coding: utf-8 -*-
"""TELG 全链路回归测试（mock 模式）"""
import os
from playwright.sync_api import sync_playwright

results = []
def log(name, ok, detail=''):
    results.append((name, ok, detail))
    print(('PASS' if ok else 'FAIL'), '|', name, ('| ' + detail if detail else ''), flush=True)

with sync_playwright() as p:
    CHROME = '/opt/vm/preinstall/ms-playwright/chromium-1169/chrome-linux/chrome'
    b = p.chromium.launch(**({'executable_path': CHROME, 'args': ['--no-sandbox']} if os.path.exists(CHROME) else {'args': ['--no-sandbox']}))
    pg = b.new_page(viewport={'width':1440,'height':900})
    errs=[]; cons=[]
    pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.on('console', lambda m: cons.append(m.text) if m.type=='error' else None)
    pg.add_init_script("try{localStorage.setItem('telg-test-data','tire')}catch(e){}")
    pg.goto('file:///home/user/Doubao/chats/38441710896760066/telg-project/frontend/index.html'); pg.wait_for_timeout(600)
    pg.evaluate("localStorage.clear(); localStorage.setItem('telg-test-data','tire'); location.reload(); true"); pg.wait_for_timeout(800)

    log('A1 页面加载无 JS 错误', len(errs)==0, '; '.join(errs[:3]))

    pg.keyboard.press('Control+k'); pg.wait_for_timeout(300)
    log('B1 ⌘K 打开生成面板', not pg.evaluate("document.getElementById('gen-panel').classList.contains('hidden')"))
    pg.evaluate("document.getElementById('topic-input').value='Brake-by-Wire Failover'; true"); pg.wait_for_timeout(100)
    pg.evaluate("document.getElementById('btn-generate').click(); true"); pg.wait_for_timeout(300)
    steps = pg.evaluate("document.querySelectorAll('#gen-progress-box .gen-step').length")
    log('B2 生成进度 3 步显示', steps==3, f'steps={steps}')
    pg.wait_for_timeout(2200)
    log('B3 语料就绪后预览出现', not pg.evaluate("document.getElementById('transcript-body').classList.contains('hidden')"))
    log('B4 语料态无 Publish 按钮', pg.evaluate("document.getElementById('btn-publish').classList.contains('hidden')"))
    log('B5 toast 提示语料已生成', 'Corpus generated' in pg.evaluate("document.querySelector('.toast') ? document.querySelector('.toast').textContent : ''"))
    log('B6 素材进入库列表', pg.evaluate("document.querySelectorAll('.lib-item').length") >= 4)
    cur = pg.evaluate("(()=>{const m=document.querySelector('.lib-item.active'); return m?m.textContent:'N/A'})()")
    log('B7 当前素材为新生成', 'Brake-by-Wire' in cur, cur)

    pg.evaluate("document.getElementById('btn-voice').click(); true"); pg.wait_for_timeout(400)
    log('C1 打开 Adjust 面板', not pg.evaluate("document.getElementById('adjust-modal').classList.contains('hidden')"))
    pg.evaluate("document.querySelector('#adjust-modal .m-tab[data-atab=\\'voice\\']').click(); true"); pg.wait_for_timeout(400)
    pg.evaluate("(()=>{const a=document.getElementById('cfg-voice-a'); if(a)a.value='en-US-ChristopherNeural'; const s=document.getElementById('cfg-voice-style'); if(s)s.value='serious'; document.getElementById('btn-adjust-apply').click();})()"); pg.wait_for_timeout(300)
    log('C2 音色应用后进入 TTS 合成进度', not pg.evaluate("document.getElementById('gen-progress-box').classList.contains('hidden')"))
    pg.wait_for_timeout(2200)
    log('C3 合成完成 audioReady', pg.evaluate("(document.querySelector('.lib-item.active') ? currentArtifact().meta.audioReady : false) == true"))
    log('C4 合成后出现 Publish', not pg.evaluate("document.getElementById('btn-publish').classList.contains('hidden')"))
    log('C5 合成后自动播放中', pg.evaluate("state.playing") is True)

    pg.evaluate("document.getElementById('btn-publish').click(); true"); pg.wait_for_timeout(300)
    log('D1 发布弹窗出现', not pg.evaluate("document.getElementById('publish-modal').classList.contains('hidden')"))
    pg.evaluate("(()=>{const i=document.querySelector('#publish-modal input'); i.value='Brake-by-Wire Failover (Final)'; document.querySelector('#publish-modal .btn-primary').click();})()"); pg.wait_for_timeout(400)
    lib = pg.evaluate("Array.from(document.querySelectorAll('.lib-item .lib-item-name')).map(x=>x.textContent)")
    log('D2 发布后库中为最终名', any('Brake-by-Wire Failover (Final)' in x for x in lib), str(lib[-2:]))
    log('D3 发布后进度/发布区隐藏', pg.evaluate("document.getElementById('gen-phases').classList.contains('hidden')"))

    pg.evaluate("(()=>{const items=document.querySelectorAll('.lib-item'); const it=Array.from(items).find(x=>x.textContent.includes('Tire Burst')); it.querySelector('.lib-item-actions [data-act=\\'rename\\']').click();})()"); pg.wait_for_timeout(300)
    pg.evaluate("(()=>{const i=document.querySelector('.lib-rename-input'); i.value='Tire Burst (Renamed)'; i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));})()"); pg.wait_for_timeout(300)
    log('E1 列表项重命名生效', 'Tire Burst (Renamed)' in pg.evaluate("document.querySelector('#lib-list').textContent"))

    pg.evaluate("(()=>{const items=document.querySelectorAll('.lib-item'); const it=Array.from(items).find(x=>x.textContent.includes('CAN Bus')); it.querySelector('.lib-item-actions [data-act=\\'delete\\']').click();})()"); pg.wait_for_timeout(300)
    log('F1 删除弹窗出现', not pg.evaluate("document.getElementById('confirm-modal').classList.contains('hidden')"))
    pg.evaluate("document.querySelector('#confirm-modal .btn-danger').click(); true"); pg.wait_for_timeout(300)
    log('F2 确认删除后素材移除', 'CAN Bus' not in pg.evaluate("document.querySelector('#lib-list').textContent"))
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)

    pg.evaluate("document.getElementById('btn-new-playlist').click(); true"); pg.wait_for_timeout(300)
    pg.evaluate("(()=>{const i=document.querySelector('.pl-rename-input'); i.value='Chassis Testing'; i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));})()"); pg.wait_for_timeout(300)
    log('G1 新建播放列表', 'Chassis Testing' in pg.evaluate("document.querySelector('#playlist-list').textContent"))
    pg.evaluate("document.getElementById('btn-add-pl').click(); true"); pg.wait_for_timeout(300)
    log('G2 添加到播放列表弹窗', not pg.evaluate("document.getElementById('pl-modal').classList.contains('hidden')"))
    pg.evaluate("(()=>{const t=Array.from(document.querySelectorAll('#pl-modal .pl-row')).find(x=>x.textContent.includes('Chassis Testing')); t.click();})()"); pg.wait_for_timeout(300)
    log('G3 素材加入列表', 'Chassis Testing' in pg.evaluate("document.querySelector('#playlist-list').textContent") and '2' in pg.evaluate("Array.from(document.querySelectorAll('#playlist-list .playlist-row')).map(x=>x.textContent).join('|')"), pg.evaluate("Array.from(document.querySelectorAll('#playlist-list .playlist-row')).map(x=>x.textContent).join('|')"))
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)

    pg.evaluate("document.getElementById('btn-engine-config').click(); true"); pg.wait_for_timeout(300)
    log('H1 设置弹窗打开', not pg.evaluate("document.getElementById('engine-modal').classList.contains('hidden')"))
    tabs = pg.evaluate("document.querySelectorAll('#engine-modal .s-nav-item').length")
    log('H2 设置 Tab 数=6', tabs==6, f'tabs={tabs}')
    pg.evaluate("document.querySelector('#cfg-theme-seg .seg-item[data-theme-opt=\\'light\\']').click(); true"); pg.wait_for_timeout(200)
    pg.evaluate("document.querySelector('#btn-modal-save').click(); true"); pg.wait_for_timeout(300)
    t1 = pg.evaluate("document.documentElement.dataset.theme")
    log('H3 应用后主题切浅色', t1 == 'light', f'theme={t1}')
    pg.evaluate("document.getElementById('btn-engine-config').click(); true"); pg.wait_for_timeout(300)
    pg.evaluate("document.querySelector('#cfg-theme-seg .seg-item[data-theme-opt=\\'dark\\']').click(); true"); pg.wait_for_timeout(200)
    pg.evaluate("document.querySelector('#btn-modal-save').click(); true"); pg.wait_for_timeout(300)

    pg.evaluate("document.getElementById('btn-engine-config').click(); true"); pg.wait_for_timeout(300)
    pg.evaluate("(()=>{const s=document.getElementById('cfg-lang'); s.value='zh'; s.dispatchEvent(new Event('change',{bubbles:true}));})()"); pg.wait_for_timeout(200)
    pg.evaluate("document.querySelector('#btn-modal-save').click(); true"); pg.wait_for_timeout(300)
    zh = pg.evaluate("document.querySelector('#engine-modal .modal-head .t-15').textContent")
    log('H4 应用后语言切中文', '设置' in zh, zh)
    pg.evaluate("document.getElementById('btn-engine-config').click(); true"); pg.wait_for_timeout(300)
    pg.evaluate("(()=>{const s=document.getElementById('cfg-lang'); s.value='en'; s.dispatchEvent(new Event('change',{bubbles:true}));})()"); pg.wait_for_timeout(200)
    pg.evaluate("document.querySelector('#btn-modal-save').click(); true"); pg.wait_for_timeout(300)

    pg.evaluate("document.getElementById('btn-engine-config').click(); true"); pg.wait_for_timeout(300)
    pg.evaluate("document.querySelector('#engine-modal .s-nav-item[data-mtab=\\'llm\\']').click(); true"); pg.wait_for_timeout(300)
    pg.evaluate("(()=>{const i=document.getElementById('cfg-llm-key'); i.type='password'; document.getElementById('btn-key-eye').click();})()"); pg.wait_for_timeout(200)
    log('H5 Key 眼睛切换明文', pg.evaluate("document.getElementById('cfg-llm-key').type")=='text')
    pg.evaluate("document.querySelector('#engine-modal .s-nav-item[data-mtab=\\'general\\']').click(); true"); pg.wait_for_timeout(300)
    zhOn = pg.evaluate("document.querySelector('#cfg-zh-seg .seg-item.active').dataset.zhOpt")
    pg.evaluate("document.querySelector('#cfg-zh-seg .seg-item[data-zh-opt=\\'off\\']').click(); true"); pg.wait_for_timeout(300)
    zhOff = pg.evaluate("document.querySelector('#cfg-zh-seg .seg-item.active').dataset.zhOpt")
    log('H6 中文字幕开关切换', zhOn=='on' and zhOff=='off', f'{zhOn}->{zhOff}')
    pg.evaluate("document.querySelector('#btn-modal-save').click(); true"); pg.wait_for_timeout(300)
    log('H7 设置保存到 localStorage', 'telg-settings' in pg.evaluate("Object.keys(localStorage)"))

    pg.keyboard.press('Space'); pg.wait_for_timeout(300)
    log('I1 Space 暂停生效', pg.evaluate("state.playing") is False)
    pg.keyboard.press('Space'); pg.wait_for_timeout(200)
    pg.evaluate("document.getElementById('btn-pb-speed').click(); true"); pg.wait_for_timeout(300)
    pg.evaluate("(()=>{const t=Array.from(document.querySelectorAll('#speed-menu button')).find(x=>x.textContent.trim().startsWith('1.5')); t.click();})()"); pg.wait_for_timeout(200)
    log('I2 倍速切 1.5x', pg.evaluate("document.getElementById('pb-speed-label').textContent")=='1.5x', pg.evaluate("document.getElementById('pb-speed-label').textContent"))
    pg.keyboard.press('k'); pg.wait_for_timeout(200)
    idx1 = pg.evaluate("currentSegIndex()")
    pg.keyboard.press('j'); pg.wait_for_timeout(200)
    idx2 = pg.evaluate("currentSegIndex()")
    log('I3 K/J 前后句切换', idx1>idx2, f'{idx2}->{idx1}')
    pg.evaluate("document.getElementById('btn-pb-subs').click(); true"); pg.wait_for_timeout(300)
    log('I4 详情面板收起', pg.evaluate("document.getElementById('inspector').classList.contains('hidden')"))
    pg.evaluate("document.getElementById('btn-pb-subs').click(); true"); pg.wait_for_timeout(200)

    pg.set_viewport_size({'width':900,'height':700}); pg.wait_for_timeout(500)
    ov1 = pg.evaluate("document.documentElement.scrollWidth - window.innerWidth")
    log('J1 900px 无横向溢出', ov1<=0, f'overflow={ov1}')
    pg.set_viewport_size({'width':620,'height':700}); pg.wait_for_timeout(500)
    ov2 = pg.evaluate("document.documentElement.scrollWidth - window.innerWidth")
    log('J2 620px 无横向溢出', ov2<=0, f'overflow={ov2}')

    print('\n===== SUMMARY =====', flush=True)
    passed = sum(1 for _,ok,_ in results if ok)
    print(f'{passed}/{len(results)} passed', flush=True)
    print('JS errors:', errs, flush=True)
    print('console errors:', cons[:5], flush=True)
    b.close()
