const state = {
  theme: localStorage.getItem('telg-theme') || 'dark',
  lang: localStorage.getItem('telg-lang') || 'en',
  zhVisible: true,
  generating: false,
  library: [],
  current: null,            /* artifact being played */
  playing: false,
  time: 0,
  speedIdx: 1,              /* 1.0x */
  seekStep: 10,             /* player rewind/forward seconds */
  goalMin: 30,              /* daily listening target in minutes */
  volume: 0.75,
  loop: false,
  autoNarr: (JSON.parse(localStorage.getItem('telg-settings') || 'null') || {}).autoNarr !== false,
  narrVoice: (JSON.parse(localStorage.getItem('telg-settings') || 'null') || {}).narrVoice || 'en-US-JennyNeural',
  narrOnly: false,           /* playing the narration segment alone */
  queuePlay: true,          /* continuous playback inside an active playlist */
  bookmarks: [],            /* [{mid, title, idx, speaker, text, time, ts}] persisted to localStorage */
  stats: { date: '', playSec: 0, quizTotal: 0, quizCorrect: 0 },
  listenMode: 'normal',
  ttsVoicesByProvider: {},
  fontIdx: 0,
  query: '',
  filters: [],
  generated: null,
  playlists: [
    { id: 'pl-vd', name: 'Vehicle Dynamics & Chassis', materialIds: ['m1', 'm3'] },
    { id: 'pl-int', name: 'Technical Interview Prep', materialIds: ['m2'] },
    { id: 'pl-ad', name: 'Autonomous Driving Planning', materialIds: ['m3'] },
    { id: 'pl-emb', name: 'Embedded Debugging & RTOS', materialIds: ['m2'] }
  ],
  activePlaylist: null,
  plRenamingId: null,
  plCreating: false,
  plModalTarget: null,
  confirm: null,
  /* v2: scene-simulation state for the generator panel */
  genScene: {
    format: 'dialogue',        /* solo | dialogue | discussion */
    domain: null,              /* {id, name} selected practice domain */
    roles: [],                 /* selected roles (solo:1, dialogue:2, discussion:candidates) */
    speakerCount: 3,           /* discussion headcount (3–5) */
    context: '',               /* free-text scene context */
    manageDomains: false,      /* manage mode for the domain chips (show × on custom) */
    manageRoles: false         /* manage mode for the role chips (show × on custom) */
  },
  profileEditing: false        /* settings: learning-preference form expanded */
};
let timer = null;

const $ = id => document.getElementById(id);

/* ---------------- HELPERS ---------------- */
function fmt(ms) {
  const s = Math.max(0, Math.floor(ms / 1000));
  return String(Math.floor(s / 60)).padStart(2, '0') + ':' + String(s % 60).padStart(2, '0');
}
function currentArtifact() { return state.current || state.library[0]; }
function escapeHtml(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }

/* ---------------- I18N ---------------- */
const I18N = {
  en: {
    'nav.generate': 'New material…', 'nav.engine': 'Settings', 'nav.new': 'New Material', 'nav.newSub': 'Generate · ⌘K',
    'sidebar.search': 'Search technical topics, terms...', 'sidebar.materials': 'My Materials', 'sidebar.playlists': 'Playlists', 'sidebar.today': "Today's Ear Training",
    'mode.normal': 'Normal', 'mode.blind': 'Blind', 'mode.export': 'MD Export',
    'pb.queue': 'Queue',
    'pl.queueOn': 'Queue playback on', 'pl.queueOff': 'Queue playback off', 'pl.remove': 'Remove from playlist',
    'bm.title': 'Phrase Bookmarks', 'bm.sub': 'Saved phrases across materials — click to jump.', 'bm.empty': 'No bookmarks yet',
    'bm.added': 'Bookmarked · ', 'bm.exists': 'Already bookmarked', 'bm.removed': 'Bookmark removed', 'bm.cleared': 'Bookmarks cleared', 'bm.clear': 'Clear all', 'bm.done': 'Done',
    'tab.grounding': 'Grounding', 'tab.vocab': 'Vocabulary', 'tab.quiz': 'Quiz', 'tab.patterns': 'Patterns',
    'tr.header': 'Synchronized Technical Dialogue', 'tr.zh': 'CN',
    'tr.synth': 'Corpus generated — audio not synthesized yet.',
    'gen.title': 'New Material', 'gen.domain': 'Domain', 'gen.add': 'Add', 'gen.addCustom': 'Add custom…', 'gen.addedRec': 'Added, synced to Settings → Recommended Defaults', 'gen.dupRec': 'This item already exists',
    'gen.tipFormat': 'The structure and speaker count of the scene: solo talk, two-person dialogue or group discussion. Switching formats adjusts how roles are picked.', 'gen.labelDuration': 'Dialogue Duration', 'gen.labelVocab': 'Vocabulary Level', 'gen.labelSyntax': 'Syntax Complexity', 'gen.vocab1': 'Life-style', 'gen.vocab2': 'Workplace', 'gen.vocab3': 'Technical', 'gen.vocab4': 'Specialized', 'gen.vocab5': 'Academic', 'gen.syntax1': 'Simple', 'gen.syntax2': 'Basic', 'gen.syntax3': 'Common', 'gen.syntax4': 'Complex', 'gen.syntax5': 'Academic', 'gen.tipDuration': 'Rough duration of the generated audio — longer means more content.', 'gen.tipVocab': 'Vocabulary range, from L1 everyday language to L5 academic terminology.', 'gen.tipSyntax': 'Syntactic complexity, from L1 simple sentences to L5 academic passages.', 'gen.tipDomain': 'Domain of the material (technical, workplace, business, academic…) — steers terminology and context. Custom domains can be added or removed.', 'gen.tipRole': 'Pick the people in the conversation: 1 for a solo talk, 2 for a dialogue; for a discussion these act as a candidate pool and AI picks who appears.', 'gen.tipContext': 'Primary basis for the material. Be specific — occasion, participants and topic all matter.', 'gen.contextNote': 'The scene context is the primary basis for generation — the more specific, the better. If it conflicts with the options above, the scene context wins.', 'gen.lenHints': {'120':'~240 words','300':'~725 words','480':'~1160 words','720':'~1740 words','900':'~2175 words'}, 'gen.cancel': 'Cancel', 'gen.contextRequired': 'Please enter a scene context first', 'gen.waiting': 'Generating… feel free to browse or play existing materials.', 'gen.switchHint': 'A material is being generated — it will appear in the library when ready.', 'pl.skipUnsynth': 'Skipped a material without audio', 'gen.vocabNames': ['','Everyday','Workplace','Technical','Specialized','Academic'], 'gen.vocabDescs': ['','Casual daily language, close to real life','Basic business communication, common workplace phrases','Core technical terms, common engineering expressions','Domain-specific vocabulary, precise technical wording','Academic-grade vocabulary, close to papers and lectures'], 'gen.syntaxNames': ['','Simple','Basic','Common','Complex','Academic'], 'gen.syntaxDescs': ['','Short sentences, straightforward structure','Simple coordinated structures, basic connectors','Common subordinate clauses, layered expression','Multiple nested clauses, varied sentence patterns','Frequent long complex sentences, academic style'],'gen.sceneSec': 'Scene Simulation', 'gen.outputSec': 'Output', 'gen.roleHint': '3–5 speakers will be picked from the roles below for a group discussion.', 'gen.roleHintSolo': 'One speaker will be picked from the roles below for a solo talk.', 'gen.roleHintDialogue': 'Two speakers will be picked from the roles below for a dialogue.',
    'gen.fmt': 'Conversation Format', 'gen.fmtSolo': 'Solo Talk', 'gen.fmtDialogue': 'Dialogue', 'gen.fmtDiscussion': 'Discussion',
    'gen.custom': 'Custom', 'gen.roles': 'Speakers',
    'gen.removedRec': 'Removed', 'gen.context': 'Scene Context', 'gen.contextPh': 'Describe the occasion and topic — e.g. test drive: the sales consultant presents vehicle performance and answers customer concerns',
    'ctxSolo': ['Technical presentation of a new solution', 'Deep-dive into one failure mechanism', 'Classroom-style lecture with brief Q&A'],
    'ctxDialogue': ['Interview: recruiter asks a candidate', 'Sales: consultant presents and handles concerns', 'Collaboration: two colleagues align on a plan'],
    'ctxDiscussion': ['Review meeting on a recent quality issue', 'Cross-team trade-off discussion', 'Supplier review with multiple stakeholders'],
    'depthLabels': { 1: 'Overview level', 2: 'Core concepts', 3: 'Mechanism + trade-offs', 4: 'Deep-dive · math & formulas', 5: 'Principal · research-level' },
    'gen.advanced': 'Advanced Directives', 'gen.generate': 'Generate',
    'gen.llmNa': 'Not configured — set in Settings', 'gen.llmNaHint': 'Add an LLM provider and API key in Settings to enable generation.',
    'pb.details': 'Details',
    'settings.title': 'Settings',
    
    'settings.tab.general': 'General', 'settings.tab.llm': 'LLM', 'settings.tab.tts': 'TTS', 'settings.tab.shortcuts': 'Shortcuts', 'settings.tab.usage': 'Usage', 'settings.tab.developer': 'Developer', 'settings.tab.study': 'Study', 'settings.rec.gen': 'Generate with LLM', 'settings.rec.noKey': 'Configure an LLM key in Settings first', 'settings.rec.genBusy': 'Generating…', 'settings.rec.generated': 'Recommendations generated', 'settings.rec.genFail': 'Failed to generate recommendations', 'settings.tab.about': 'About',
    'settings.study.sub': 'Listening time tracked per day — seconds actually played.',
    'settings.study.total': 'Total',
    'settings.study.secGoal': 'Training Goal', 'settings.goal.daily': 'Daily Listening Target', 'settings.goal.hint': 'Minutes of listening per day — tracked in the stats below.',
    'settings.profile.rolePortrait': 'Speaker Setting · AI-drafted, editable',
    'settings.profile.domainProfile': 'Domain Profile', 'settings.profile.focusTone': 'Focus & Tone', 'settings.profile.generating': 'Generating profile…',
    'welcome.create': 'Create & Start', 'welcome.login': 'Log in', 'welcome.switch': 'Already have an account? Log in', 'welcome.switchLogin': 'New here? Create an account',
    'welcome.guest': 'Continue as guest', 'welcome.sub': 'Create a local account to start.', 'welcome.subLogin': 'Sign in to continue.',
    'welcome.needUser': 'Enter a username', 'welcome.pwShort': 'Password too short (min 4)', 'welcome.hasAccount': 'An account already exists on this device', 'welcome.noAccount': 'No local account — create one first',
    'welcome.wrongUser': 'Unknown username', 'welcome.wrongPw': 'Wrong password', 'welcome.pwMismatch': 'Passwords do not match', 'welcome.back': 'Back', 'welcome.next': 'Next', 'welcome.ready': 'Welcome! Your workspace is ready.',
    'ob.llmTitle': 'Set up your LLM', 'ob.llmSub': 'Materials are generated by an LLM. Fill in the provider below and pass a connection test to continue.', 'ob.llmProvider': 'LLM Provider', 'ob.llmModel': 'Model', 'ob.llmBase': 'Base URL', 'ob.llmKey': 'API Key',
    'ob.llmTest': 'Test Connection', 'ob.llmTesting': 'Testing…', 'ob.llmTestOk': 'Connection OK — you can continue.', 'ob.llmTestFail': 'Connection test failed', 'ob.llmNextHint': '“Next” unlocks once the connection test passes.',
    'ob.llmSkip': 'Skip — use test data for now',
    'ob.surveyTitle': 'Personalization', 'ob.surveySub': 'Tell us a little about yourself — review and save at the end.', 'ob.confirm': 'Review & Save', 'ob.qRole': 'Your role / position', 'ob.qRoleHint': 'e.g. Controls Algorithm Engineer, Student',
    'ob.qDomain': 'Primary practice domain', 'ob.qDomainHint': 'Type the domain you work in, e.g. Semiconductor.', 'ob.qLang': 'Language direction', 'ob.qLangHint': 'Learning language + translation. EN ↔ ZH is available now.',
    'ob.qMin': 'Daily listening target', 'ob.qMinHint': 'Minutes per day — becomes your Training Goal.',
    'ob.chipEnZh': 'EN ↔ ZH', 'ob.chipJaZh': 'JA ↔ ZH', 'ob.chipDeZh': 'DE ↔ ZH', 'ob.chipFrZh': 'FR ↔ ZH', 'ob.langWip': 'Coming soon', 'ob.profileTitle': 'Confirm your profile', 'ob.profileSub': 'Review the summary, generate a detailed profile with LLM (optional), then finish.',
    'ob.role': 'Role', 'ob.domain': 'Domain', 'ob.lang': 'Language', 'ob.min': 'Daily minutes',
    'ob.profileHint': 'Generate a detailed role portrait, domain profile and tone with the LLM — editable, or finish with raw answers.', 'ob.genProfile': 'Generate with LLM', 'ob.finish': 'Finish & Enter', 'ob.needDomain': 'Enter a domain first', 'ob.needMin': 'Enter a daily minute target',
    'settings.about.account': 'Account', 'settings.about.accountName': 'Local Account', 'settings.about.login': 'Log in', 'settings.about.logout': 'Log out', 'settings.about.signedOut': 'Signed out', 'settings.about.guest': 'Guest — no local account.',
    'settings.developer.sub': 'LLM link debugging and corpus take-over for the TTS pipeline.',
    'settings.developer.llmDiag': 'LLM Diagnostics',
    'settings.developer.llmMock': 'LLM Mock', 'settings.developer.llmMockHint': 'LLM link debugging — real call with the configured key; intermediate steps shown on the main page. No key → real failure reported.',
    'settings.developer.reqResp': 'LLM Request / Response',
    'settings.developer.promptPrev': 'LLM Prompt Preview', 'settings.developer.promptPrevHint': 'Shows the exact system + user prompt assembled from the current generation panel settings. No LLM call.',
    'settings.developer.promptPrevBtn': 'Show Prompt',
    'settings.developer.testData': 'Test Data',
    'settings.developer.ttsMockSec': 'TTS Mock',
    'settings.developer.ttsMock': 'TTS Mock', 'settings.developer.ttsMockHint': 'Corpus take-over — generate from the selected dataset. Audio synthesis, audition and playback stay fully real.',
    'settings.developer.testDataHint': 'Corpus source for take-over — the selected dataset replaces the LLM result.',
    'settings.shortcuts.sub': 'Global keyboard shortcuts — work wherever the app is focused.',
    'settings.about.sub': 'Scenear — scene-based bilingual listening materials, crafted for your ears.',
    'settings.about.product': 'Product', 'settings.about.version': 'Version', 'settings.about.versionDesc': 'v0.1.0 — single-file frontend, FastAPI backend.',
    'settings.about.engine': 'Engines', 'settings.about.engineDesc': 'LLM: OpenAI-compatible — DeepSeek / Kimi / Ark / Qwen / Ollama. TTS: edge-tts / Piper / CosyVoice.',
    'settings.about.backend': 'Backend Contract', 'settings.about.backendDesc': 'GET /api/v1/health · POST /api/v1/generate · GET/PATCH/DELETE /api/v1/materials · POST /materials/:id/synthesize',
    'settings.about.status': 'Status', 'settings.about.statusDesc': 'Live backend by default; Test Data in Developer settings switches to fixed templates.', 'settings.about.mock': 'Mock',
    'settings.about.legal': 'Legal', 'settings.about.copy': '© 2026 Scenear — crafted for your ears. Scenes that resonate.',
    'settings.lang.label': 'Interface Language', 'settings.lang.hint': 'UI chrome only — technical content stays in English.',
    'settings.appearance.label': 'Appearance', 'settings.theme.dark': 'Dark', 'settings.theme.light': 'Light',
    'settings.zh.on': 'On', 'settings.zh.off': 'Off',
    'settings.general.sub': 'Software-wide defaults — language, appearance, playback.',
    'settings.usage.sub': 'LLM token consumption — successful calls only.', 'settings.usage.loading': 'Loading…',
    'settings.usage.unavailable': 'Usage unavailable — backend not reachable.',
    'settings.usage.total': 'Total',
    'settings.usage.today': 'Today',
    'settings.usage.trend': 'Trend',
    'settings.usage.now': 'Now',
    'settings.usage.viewDay': 'Day',
    'settings.usage.viewWeek': 'Week',
    'settings.usage.viewMonth': 'Month',
    'settings.usage.viewYear': 'Year',
    'settings.llm.sub': 'OpenAI-compatible generation backend used by the /generate pipeline.',
    'settings.tts.sub': 'Sentence-by-sentence synthesis; segments are stitched into a single timeline with start_ms / end_ms.',
    'settings.llm.provider': 'LLM Provider',
    'settings.llm.params': 'Generation Parameters', 'settings.llm.temphint': 'Lower favors stable JSON; higher favors creativity.',
    'settings.tts.provider': 'TTS Provider',
    'settings.tts.rate': 'Speech Rate', 'settings.tts.ratehint': 'Applied at synthesis time; player speed stays independent.',
    'settings.tts.addRole': 'Add role',
    'settings.shortcuts.label': 'Keyboard Shortcuts',
    'settings.shortcuts.gen': 'Generate panel', 'settings.shortcuts.play': 'Play / Pause', 'settings.shortcuts.sent': 'Prev / Next sentence', 'settings.shortcuts.replay': 'Replay sentence', 'settings.shortcuts.search': 'Search library',
    'settings.cancel': 'Cancel', 'settings.save': 'Apply Settings',
    'settings.mode': 'Mock mode — provider settings persist locally for the real integration.',
    'settings.saved': 'Settings applied',
    'settings.llm.test': 'Connection Test', 'settings.llm.testBtn': 'Test Connection', 'settings.llm.testing': 'Testing…', 'settings.llm.ok': 'Connected', 'settings.llm.genTestBtn': 'Test Generation', 'settings.llm.genTesting': 'Running…',
    'settings.llm.unlockPh': 'Enter dev key',
    'settings.dev.label': 'Developer Mode', 'settings.dev.sub': 'Master switch — debug tools below are only available while ON. Release builds require a key.',
    'settings.general.secInterface': 'Interface', 'settings.general.secPlayback': 'Playback',
    'settings.appearance.hint': 'Dark / Light — saved on Apply.',
    'settings.playback.speed': 'Default Speed', 'settings.playback.speedhint': 'Playback speed for newly opened materials.', 'settings.playback.seek': 'Seek Step', 'settings.playback.seekhint': 'Rewind / forward step for the player buttons.', 'settings.playback.narr': 'Auto Narrate', 'settings.playback.narrhint': 'Play the storyline narration before the dialogue when playback starts. The narration always counts into the total duration.', 'settings.tts.narrVoice': 'Narration Voice', 'settings.tts.narrVoicehint': 'Default voice for the storyline narration.', 'narr.badge': 'Story · Narration', 'narr.play': 'Play Narration', 'quiz.jump': 'Listen to the sentence',
    'settings.playback.zh': 'Chinese Subtitles', 'settings.playback.zhhint': 'Whether the Chinese line is shown by default.',
    'settings.llm.secEndpoint': 'Endpoint & Credentials', 'settings.llm.secParams': 'Generation Parameters',
    'settings.llm.testhint': 'Verifies base_url / api_key / model reachability.',
    'settings.llm.genTestHint': 'Runs the full pipeline without saving to library.',
    'settings.llm.model': 'Model', 'settings.llm.base': 'Base URL', 'settings.llm.key': 'API Key',
    'settings.llm.modelhint': 'Provider-specific identifier, e.g. deepseek-chat.',
    'settings.llm.basehint': 'Provider API root — no /chat/completions suffix.',
    'settings.llm.providerhint': 'OpenAI-compatible protocol — selection pre-fills Base URL and model.',
    'settings.llm.credshint': 'Root URL without /chat/completions. The key is stored in this browser only (localStorage) and sent only with your requests; it is never uploaded to any third-party service.',
    'settings.tts.secEngine': 'Synthesis Engine',
    'settings.tts.voice': 'Voice Roles', 'settings.tts.voicehint': 'Type text, then play to audition.',
    'settings.tts.roleName': 'Role name', 'settings.tts.audition': 'Audition this voice', 'settings.tts.delRole': 'Remove role',
    'settings.tts.testTextPh': 'Enter text to audition with each role…',
    'settings.tts.providerhint': 'edge-tts: no key · Kokoro: offline · CosyVoice: GPU.',
    'settings.tts.ok': 'Voice OK',
    'settings.test.err': 'Failed',
    'err.tts.timeout': 'TTS connection timeout — the TTS service is unreachable. Check network, proxy or firewall, then retry.',
    'err.tts.unreachable': 'TTS service unreachable — check network, proxy or firewall, then retry.',
    'err.tts.auth': 'TTS service rejected the request (authentication / token).',
    'err.tts.other': 'TTS synthesis failed.',
    'err.tts.model_missing': 'TTS model not downloaded — see backend console for the download path.',
    'err.audio': 'Audio file unavailable — re-synthesize to restore playback.',
    'err.retry': 'Retry',
    'tts.voice': 'Voice', 'tts.setVoice': 'Set Voice & Synthesize',
    'tts.presetDesc': 'Quick-select a matching two-voice combination.',
    'tts.speakerADesc': 'Voice used for the first speaker.',
    'tts.speakerBDesc': 'Voice used for the second speaker.',
    'tts.rateDesc': 'Playback cadence of the synthesized audio.',
    'tts.styleDesc': 'Emotional color applied to the voices.',
    'adjust.open': 'Adjust', 'adjust.title': 'Adjust Material',
    'adjust.titleCorpus': 'Edit Corpus', 'adjust.subCorpus': 'Adjust the parameters, then regenerate the corpus.',
    'adjust.titleVoice': 'Voice Settings', 'adjust.subVoice': 'Configure TTS voice, rate and style for this material.',
    'adjust.tabText': 'Text', 'adjust.tabVoice': 'Voice',
    'adjust.textSub': 'Corpus Text', 'adjust.textHint': 'Adjust parameters or add directives, then regenerate the corpus.',
    'tts.title': 'Voice & TTS Settings', 'tts.sub': 'Choose voices and convert the current material.',
    'tts.target': 'Target material — converted with the settings below.',
    'tts.preset': 'Voice Pair Preset', 'tts.speakerA': 'Speaker A', 'tts.speakerB': 'Speaker B',
    'tts.convert': 'Apply & Convert', 'tts.reconvert': 'Re-synthesize',
    'tts.singleHint': 'Single-speaker dialogue — one voice is enough. Extra voices will be used in order.',
    'tts.statusReady': 'Corpus ready — not synthesized yet.',
    'tts.statusExist': 'Audio exists — re-converting will replace it.',
    'tr.regenerate': 'Regenerate', 'tr.refine': 'Edit Corpus…', 'tr.editAudio': 'Edit Audio Settings', 'tr.audioReady': 'Audio ready — review and publish.',
    'refine.title': 'Refine Generation', 'refine.sub': 'Adjust parameters or add directives, then regenerate the corpus.',
    'refine.topic': 'Topic', 'refine.domain': 'Domain', 'refine.role': 'Role', 'refine.scenario': 'Scenario',
    'refine.difficulty': 'Vocabulary Level', 'refine.difficultyDesc': 'Vocabulary range, from L1 everyday language to L5 academic terminology.',
    'refine.length': 'Dialogue Duration', 'refine.lengthDesc': 'Rough duration of the generated audio — longer means more content.',
    'refine.depth': 'Syntax Complexity', 'refine.depthDesc': 'Syntactic complexity, from L1 simple sentences to L5 academic passages.',
            'refine.secCore': 'Core', 'refine.secScope': 'Depth & Scope', 'refine.secDirectives': 'Directives', 'refine.secDir': 'Direction',
    'refine.inject': 'Improvement Directives', 'refine.injectPh': 'e.g. Add concrete numbers and measurements, make it more conversational…',
    'refine.injectHint': 'Optional — injected into the generation prompt.',
    'refine.dir': 'Generation Direction', 'refine.dirDesc': 'Which way to steer the rewrite.',
    'refine.dirRephrase': 'Rewrite',
    'refine.dirExpand': 'Expand',
    'refine.dirNarrow': 'Focus',
    'refine.dirAngle': 'Diverge',
    'refine.dirRephraseDesc': 'Keep the same scope, only adjust wording',
    'refine.dirExpandDesc': 'Add more technical detail',
    'refine.dirNarrowDesc': 'Focus on a single aspect',
    'refine.dirAngleDesc': 'Diverge to a different perspective',
    'refine.tipDir': 'Rewrite: keep the same scope; Expand: add more depth and detail; Focus: converge on one aspect; Diverge: reorganize from a different angle.',
    'refine.apply': 'Refine & Regenerate',
    'save.title': 'Save', 'save.saved': 'Saved', 'save.done': 'Saved to My Materials — ',
    'lib.rename': 'Rename', 'lib.delete': 'Delete', 'lib.draft': 'Draft', 'lib.unsynth': 'No audio', 'lib.clearFilters': 'Clear filters',
    'lib.renamed': 'Renamed — ', 'lib.deleted': 'Deleted — ', 'lib.empty': 'No materials yet', 'lib.nameExists': 'A material with this name already exists',
    'lib.emptyTitle': 'No materials yet', 'lib.emptySub': 'Generate a scene-based listening material from a real situation you will face.',
    'gen.tone': 'Tone & Mood',
    'tone.neutral': 'Neutral professional', 'tone.urgent': 'Urgent · deadline pressure', 'tone.interview': 'Interview · high-pressure Q&A',
    'tone.collaborative': 'Collaborative & calm', 'tone.debate': 'Confrontational debate', 'tone.mentoring': 'Explanatory mentorship',
    'tts.styleLabel': 'Emotion / Style',
    'tts.style.neutral': 'Neutral', 'tts.style.cheerful': 'Cheerful', 'tts.style.empathetic': 'Empathetic',
    'tts.style.serious': 'Serious', 'tts.style.urgent': 'Urgent', 'tts.style.whispering': 'Whispering',
    'pl.addTo': 'Playlist', 'pl.title': 'Add to Playlist', 'pl.new': 'New playlist…', 'pl.done': 'Done',
    'pl.createPh': 'Playlist name…', 'pl.in': 'in', 'pl.empty': 'No materials in this playlist', 'pl.exit': 'Exit playlist view', 'pl.all': 'All Materials',
    'pl.created': 'Playlist created — ', 'pl.renamed': 'Playlist renamed — ', 'pl.deleted': 'Playlist deleted — ', 'pl.added': 'Added to ', 'pl.removed': 'Removed from ', 'pl.nameExists': 'A playlist with this name already exists',
    'del.title': 'Delete?', 'del.mTitle': 'Delete material?', 'del.pTitle': 'Delete playlist?',
    'del.cancel': 'Cancel', 'del.delete': 'Delete',
    'del.materialText': 'This permanently deletes the material from All Materials and every playlist. It cannot be undone.',
    'del.materialInPl': 'This permanently deletes the material from All Materials and every playlist (including this one). It cannot be undone.',
    'del.playlistText': 'This deletes the playlist. Its materials stay in All Materials.',
    'gen.stepC0': 'Parsing parameters & building prompt', 'gen.stepC1': 'LLM generating technical corpus', 'gen.stepC2': 'Validating structure & technical grounding',
    'gen.stepA0': 'Synthesizing sentences via TTS', 'gen.stepA1': 'Stitching audio segments', 'gen.stepA2': 'Aligning sentence-level timeline',
    'gen.corpusLabel': 'Topic — ', 'gen.audioLabel': 'TTS synthesis — ',
    'ph.corpus': 'Corpus', 'ph.tts': 'TTS', 'ph.publish': 'Publish',
    'gen.publish': 'Publish',
    'pub.title': 'Publish Material', 'pub.sub': 'Name the material and add it to My Materials.',
    'pub.name': 'File name', 'pub.cancel': 'Cancel', 'pub.ok': 'Publish', 'pub.done': 'Published · '
  },
  zh: {
    'nav.generate': '新建素材…', 'nav.engine': '设置', 'nav.new': '新建素材', 'nav.newSub': '生成 · ⌘K',
    'sidebar.search': '搜索技术主题、术语…', 'sidebar.materials': '我的素材', 'sidebar.playlists': '播放列表', 'sidebar.today': '今日听力训练',
    'mode.normal': '常规', 'mode.blind': '盲听', 'mode.export': '导出 MD',
    'pb.queue': '队列',
    'pl.queueOn': '队列播放已开启', 'pl.queueOff': '队列播放已关闭', 'pl.remove': '移出列表',
    'bm.title': '短语收藏', 'bm.sub': '跨素材收藏的短语 — 点击跳转。', 'bm.empty': '暂无收藏',
    'bm.added': '已收藏 · ', 'bm.exists': '该句已收藏', 'bm.removed': '已取消收藏', 'bm.cleared': '已清空收藏', 'bm.clear': '清空', 'bm.done': '完成',
    'tab.grounding': '技术接地', 'tab.vocab': '词汇', 'tab.quiz': '测验', 'tab.patterns': '句型',
    'tr.header': '同步技术对话', 'tr.zh': '中文',
    'tr.synth': '语料已生成 — 音频尚未合成。',
    'gen.title': '新建素材', 'gen.domain': '领域', 'gen.add': '添加', 'gen.addCustom': '添加自定义…', 'gen.addedRec': '已添加，并同步到 设置 → 推荐设置', 'gen.dupRec': '该项已存在',
    'gen.tipFormat': '决定对话的结构与出场人数：单人讲解、双人对话或多人讨论。切换形态会同步调整角色选择方式。', 'gen.labelDuration': '对话时长', 'gen.labelVocab': '词汇专业度', 'gen.labelSyntax': '句式复杂度', 'gen.vocab1': '生活化', 'gen.vocab2': '职场化', 'gen.vocab3': '技术化', 'gen.vocab4': '专业化', 'gen.vocab5': '学术化', 'gen.syntax1': '简单', 'gen.syntax2': '基础', 'gen.syntax3': '常用', 'gen.syntax4': '复杂', 'gen.syntax5': '学术', 'gen.tipDuration': '生成音频的大致时长，时间越长内容越充分。', 'gen.tipVocab': '词汇难度范围，从 L1 生活化日常用语到 L5 学术级专业词汇。', 'gen.tipSyntax': '句法复杂程度，从 L1 简单短句到 L5 学术长难句。', 'gen.tipDomain': '素材所属领域（技术、职场、商务、学术等），影响术语选择与语境倾向。可添加或删除自定义领域。', 'gen.tipRole': '选择参与对话的人物：单人讲解选 1 位，双人对话选 2 位；多人讨论时作为候选名单，由 AI 依据语境挑选出场。', 'gen.tipContext': '生成素材的主要依据。描述越具体越好，包括场合、参与方、讨论话题等。', 'gen.contextNote': '场景语境是生成素材的主要依据，描述越具体越好。当与上述选项设置冲突时，将优先以场景语境为准。', 'gen.lenHints': {'120':'约 240 词','300':'约 725 词','480':'约 1160 词','720':'约 1740 词','900':'约 2175 词'}, 'gen.cancel': '取消', 'gen.contextRequired': '请先输入场景语境', 'gen.waiting': '生成中，可继续浏览或播放已有素材…', 'gen.switchHint': '素材正在生成中，完成后将出现在素材库', 'pl.skipUnsynth': '已跳过未合成音频的素材', 'gen.vocabNames': ['','生活化','职场化','技术化','专业化','学术化'], 'gen.vocabDescs': ['','日常聊天用语，贴近生活场景','基础商务沟通，通用职场表达','基础技术术语，常见工程表达','领域专业词汇，准确的技术用语','学术级词汇，接近论文与讲座'], 'gen.syntaxNames': ['','简单','基础','常用','复杂','学术'], 'gen.syntaxDescs': ['','短句为主，结构直白清晰','简单并列复合，连接词基础','含常用从句，表达有层次','多从句嵌套，句式富有变化','长难句频繁，学术式行文'],'gen.sceneSec': '场景模拟', 'gen.outputSec': '输出参数', 'gen.roleHint': '将从对话角色中选取 3–5 个角色，生成多人讨论。', 'gen.roleHintSolo': '将从对话角色中选取 1 个角色，生成单人讲解。', 'gen.roleHintDialogue': '将从对话角色中选取 2 个角色，生成双人对话。',
    'gen.fmt': '对话形态', 'gen.fmtSolo': '单人讲解', 'gen.fmtDialogue': '双人对话', 'gen.fmtDiscussion': '多人讨论',
    'gen.custom': '自定义', 'gen.roles': '对话角色',
    'gen.removedRec': '已删除', 'gen.context': '场景语境', 'gen.contextPh': '描述场合与主题，如：试驾环节，销售介绍车辆性能并回应客户顾虑',
    'ctxSolo': ['新技术方案的技术演讲', '深挖某个失效机理的讲解', '课堂教学式讲解（带简短问答）'],
    'ctxDialogue': ['面试：面试官提问候选人', '销售：顾问介绍产品并回应顾虑', '协作：两位同事对齐方案'],
    'ctxDiscussion': ['近期质量问题的评审会', '跨团队方案权衡讨论', '多方参与的供应商评审'],
    'depthLabels': { 1: '概览级', 2: '核心概念', 3: '机制与权衡', 4: '深入 — 公式与推导', 5: '专家级 — 研究深度' },
    'gen.advanced': '高级指令', 'gen.generate': '生成',
    'gen.llmNa': '未配置 — 前往设置添加', 'gen.llmNaHint': '在设置中添加 LLM 提供商与 API Key 后即可生成。',
    'pb.details': '详情',
    'settings.title': '设置',
    
    'settings.tab.general': '通用', 'settings.tab.llm': 'LLM', 'settings.tab.tts': 'TTS', 'settings.tab.shortcuts': '快捷键', 'settings.tab.usage': '用量', 'settings.tab.developer': '开发者', 'settings.tab.study': '学习', 'settings.rec.gen': '由 LLM 生成', 'settings.rec.noKey': '请先在设置中配置 LLM Key', 'settings.rec.genBusy': '生成中…', 'settings.rec.generated': '推荐已生成', 'settings.rec.genFail': '推荐生成失败', 'settings.tab.about': '关于',
    'settings.study.sub': '每日学习时长统计——按实际播放秒数记录。',
    'settings.study.total': '累计',
    'settings.study.secGoal': '训练目标', 'settings.goal.daily': '每日听力目标', 'settings.goal.hint': '每日学习时长目标（分钟），由下方统计跟踪进度。',
    'settings.profile.rolePortrait': '对话角色设定 · AI 生成，可编辑',
    'settings.profile.domainProfile': '领域档案', 'settings.profile.focusTone': '专注与语气', 'settings.profile.generating': '正在生成角色设定…',
    'welcome.create': '创建并开始', 'welcome.login': '登录', 'welcome.switch': '已有账号？登录', 'welcome.switchLogin': '新用户？创建账号',
    'welcome.guest': '以游客身份继续', 'welcome.sub': '创建本地账号开始使用。', 'welcome.subLogin': '登录以继续。',
    'welcome.needUser': '请输入用户名', 'welcome.pwShort': '密码太短（至少 4 位）', 'welcome.hasAccount': '本机已存在账号', 'welcome.noAccount': '本机无账号——请先创建',
    'welcome.wrongUser': '用户名不存在', 'welcome.wrongPw': '密码错误', 'welcome.pwMismatch': '两次密码不一致', 'welcome.back': '上一步', 'welcome.next': '下一步', 'welcome.ready': '欢迎！你的工作台已就绪。',
    'ob.llmTitle': '设置 LLM', 'ob.llmSub': '素材由 LLM 生成。请填写下方提供商信息并通过连接测试后继续。', 'ob.llmProvider': 'LLM 提供商', 'ob.llmModel': '模型', 'ob.llmBase': '接口地址', 'ob.llmKey': 'API 密钥',
    'ob.llmTest': '测试连接', 'ob.llmTesting': '正在测试…', 'ob.llmTestOk': '连接成功 — 可以继续。', 'ob.llmTestFail': '连接测试失败', 'ob.llmNextHint': '连接测试通过后解锁“下一步”。',
    'ob.llmSkip': '跳过 — 暂用测试数据',
    'ob.surveyTitle': '个性化设置', 'ob.surveySub': '简单介绍下自己，填写完成后统一确认并保存。', 'ob.confirm': '确认并保存', 'ob.qRole': '你的角色 / 职位', 'ob.qRoleHint': '例如：控制算法工程师、学生',
    'ob.qDomain': '主要练习领域', 'ob.qDomainHint': '填写你工作的领域，例如：半导体。', 'ob.qLang': '语言方向', 'ob.qLangHint': '学习语言 + 翻译语言。目前支持中英。',
    'ob.qMin': '每日听力目标', 'ob.qMinHint': '每天分钟数——将写入训练目标。',
    'ob.chipEnZh': '中英', 'ob.chipJaZh': '中日', 'ob.chipDeZh': '中德', 'ob.chipFrZh': '中法', 'ob.langWip': '开发中，敬请期待', 'ob.profileTitle': '确认你的档案', 'ob.profileSub': '核对摘要，可让 LLM 生成详细档案（可选），然后完成。',
    'ob.role': '角色', 'ob.domain': '领域', 'ob.lang': '语言', 'ob.min': '每日分钟',
    'ob.profileHint': '用 LLM 生成角色画像、领域档案与语气——可编辑；也可直接用原始回答完成。', 'ob.genProfile': '由 LLM 生成', 'ob.finish': '完成并进入', 'ob.needDomain': '请先填写领域', 'ob.needMin': '请输入每日分钟数',
    'settings.about.account': '账号', 'settings.about.accountName': '本地账号', 'settings.about.login': '登录', 'settings.about.logout': '登出', 'settings.about.signedOut': '已登出', 'settings.about.guest': '游客——未绑定本地账号。',
    'settings.developer.sub': 'LLM 链路调试与 TTS 语料接管。',
    'settings.developer.llmDiag': 'LLM 诊断',
    'settings.developer.reqResp': 'LLM 请求与响应',
    'settings.developer.promptPrev': 'LLM Prompt 预览', 'settings.developer.promptPrevHint': '展示当前生成面板参数实际组装出的 System + User prompt（不调用 LLM）。',
    'settings.developer.promptPrevBtn': 'Show Prompt',
    'settings.developer.llmMock': 'LLM Mock', 'settings.developer.llmMockHint': 'LLM 链路调试——使用已配置 Key 真实调用，主页面展示中间过程；未配置 Key 时如实反馈未联通。',
    'settings.developer.ttsMockSec': 'TTS Mock',
    'settings.developer.ttsMock': 'TTS Mock', 'settings.developer.ttsMockHint': '语料接管——使用所选数据集生成语料；音频合成、试听与播放保持真实。',
    'settings.developer.testData': '测试数据',
    'settings.developer.testDataHint': '语料接管的数据源——所选数据集将替代 LLM 结果。',
    'settings.shortcuts.sub': '全局快捷键——应用聚焦时均生效。',
    'settings.about.sub': '场景听——场景化双语听力素材生成器，为耳朵定制，让场景掷地有声。',
    'settings.about.product': '产品', 'settings.about.version': '版本', 'settings.about.versionDesc': 'v0.1.0——单文件前端 + FastAPI 后端。',
    'settings.about.engine': '引擎', 'settings.about.engineDesc': 'LLM：OpenAI 兼容——DeepSeek / Kimi / Ark / Qwen / Ollama。TTS：edge-tts / Piper / CosyVoice。',
    'settings.about.backend': '后端契约', 'settings.about.backendDesc': 'GET /api/v1/health · POST /api/v1/generate · GET/PATCH/DELETE /api/v1/materials · POST /materials/:id/synthesize',
    'settings.about.status': '状态', 'settings.about.statusDesc': '默认连接真实后端；开发者模式中的测试数据可切换为固定模板。', 'settings.about.mock': 'Mock',
    'settings.about.legal': '法律', 'settings.about.copy': '© 2026 场景听——为耳朵定制，让场景掷地有声。',
    'settings.lang.label': '界面语言', 'settings.lang.hint': '仅切换界面文案 — 技术内容保持英文。',
    'settings.appearance.label': '外观', 'settings.theme.dark': '深色', 'settings.theme.light': '浅色',
    'settings.zh.on': '开', 'settings.zh.off': '关',
    'settings.general.sub': '软件全局默认 — 语言、外观、播放。',
    'settings.usage.sub': 'LLM Token 消耗 — 仅统计成功调用。', 'settings.usage.loading': '加载中…',
    'settings.usage.unavailable': '用量不可用 — 后端未连接。',
    'settings.usage.total': '总计',
    'settings.usage.today': '今日',
    'settings.usage.trend': '趋势',
    'settings.usage.now': '当前',
    'settings.usage.viewDay': '日',
    'settings.usage.viewWeek': '周',
    'settings.usage.viewMonth': '月',
    'settings.usage.viewYear': '年',
    'settings.llm.sub': 'OpenAI 兼容的生成后端，由 /generate 管线使用。',
    'settings.tts.sub': '逐句合成，按 start_ms / end_ms 拼接为单一时间轴。',
    'settings.llm.provider': 'LLM 提供商',
    'settings.llm.params': '生成参数', 'settings.llm.temphint': '滑动调节：数值低更稳定，高更有创意（0.2 – 1.0）。',
    'settings.tts.provider': 'TTS 提供商',
    'settings.tts.rate': '语速', 'settings.tts.ratehint': '在合成时生效；播放器倍速独立。',
    'settings.tts.addRole': '添加角色',
    'settings.shortcuts.label': '键盘快捷键',
    'settings.shortcuts.gen': '打开生成面板', 'settings.shortcuts.play': '播放 / 暂停', 'settings.shortcuts.sent': '上一句 / 下一句', 'settings.shortcuts.replay': '重播当前句', 'settings.shortcuts.search': '搜索素材库',
    'settings.cancel': '取消', 'settings.save': '应用设置',
    'settings.mode': 'Mock 模式 — 提供商设置保存在本地，供真实集成使用。',
    'settings.saved': '设置已应用',
    'settings.llm.test': '连接测试', 'settings.llm.testBtn': '测试连接', 'settings.llm.testing': '测试中…', 'settings.llm.ok': '连接成功', 'settings.llm.genTestBtn': '测试生成', 'settings.llm.genTesting': '运行中…',
    'settings.llm.unlockPh': '输入开发者密钥',
    'settings.dev.label': '开发模式', 'settings.dev.sub': '总开关——仅开启时下方调试工具可用。正式发布版需密钥才能开启。',
    'settings.general.secInterface': '界面', 'settings.general.secPlayback': '播放',
    'settings.appearance.hint': '深色 / 浅色，应用后生效。',
    'settings.playback.speed': '默认倍速', 'settings.playback.speedhint': '新素材的默认播放倍速。', 'settings.playback.seek': '快进退步长', 'settings.playback.seekhint': '播放器前进/后退按键的步长秒数。', 'settings.playback.narr': '自动朗读旁白', 'settings.playback.narrhint': '播放开始时，先朗读情景旁白再接续正文对话。旁白时长始终计入总时长。', 'settings.tts.narrVoice': '旁白音色', 'settings.tts.narrVoicehint': '情景旁白的默认音色。', 'narr.badge': '情景引子 · 旁白', 'narr.play': '朗读旁白', 'quiz.jump': '收听原句',
    'settings.playback.zh': '中文字幕', 'settings.playback.zhhint': '默认是否显示中文字幕。',
    'settings.llm.secEndpoint': '接口与凭据', 'settings.llm.secParams': '生成参数',
    'settings.llm.testhint': '校验 base_url / api_key / model 连通性。',
    'settings.llm.genTestHint': '运行完整生成管线，不写入素材库。',
    'settings.llm.model': '模型', 'settings.llm.base': '接口地址', 'settings.llm.key': 'API 密钥',
    'settings.llm.modelhint': '服务商期望的模型标识，如 deepseek-chat。',
    'settings.llm.basehint': '服务商 API 根地址，不含 /chat/completions 后缀。',
    'settings.llm.providerhint': 'OpenAI 兼容协议——选择后自动预填 Base URL 与模型。',
    'settings.llm.credshint': '根地址不含 /chat/completions。密钥仅保存在本机浏览器（localStorage），仅随你的请求发送，不上传任何第三方服务。',
    'settings.tts.secEngine': '合成引擎',
    'settings.tts.voice': '音色角色', 'settings.tts.voicehint': '输入文字，点击播放键试听。',
    'settings.tts.roleName': '角色名', 'settings.tts.audition': '试听该音色', 'settings.tts.delRole': '删除角色',
    'settings.tts.testTextPh': '输入文字，在下方角色行试听…',
    'settings.tts.providerhint': 'edge-tts 免 Key · Kokoro 本地离线 · CosyVoice 需 GPU。',
    'settings.tts.ok': '音色可用',
    'settings.test.err': '失败',
    'err.tts.timeout': 'TTS 连接超时——TTS 服务不可达。请检查网络、代理或防火墙后重试。',
    'err.tts.unreachable': 'TTS 服务不可达——请检查网络、代理或防火墙后重试。',
    'err.tts.auth': 'TTS 服务拒绝了请求（鉴权 / 令牌问题）。',
    'err.tts.other': 'TTS 合成失败。',
    'err.tts.model_missing': 'TTS 模型未下载——请查看后端控制台提示完成模型下载。',
    'err.audio': '音频文件不可用——请重新合成以恢复播放。',
    'err.retry': '重试',
    'tts.voice': '音色', 'tts.setVoice': '设置音色并合成',
    'tts.presetDesc': '快速选择匹配的双人音色组合。',
    'tts.speakerADesc': '第一位说话人使用的音色。',
    'tts.speakerBDesc': '第二位说话人使用的音色。',
    'tts.rateDesc': '合成音频的播放语速。',
    'tts.styleDesc': '应用于音色的情感色彩。',
    'adjust.open': '调整', 'adjust.title': '调整素材',
    'adjust.titleCorpus': '调整语料', 'adjust.subCorpus': '调整参数后重新生成语料。',
    'adjust.titleVoice': '音频设置', 'adjust.subVoice': '为当前素材配置音色、语速与情感风格。',
    'adjust.tabText': '文本', 'adjust.tabVoice': '音色',
    'adjust.textSub': '语料文本', 'adjust.textHint': '调整参数或添加指令，然后重新生成语料。',
    'tts.title': '音色与 TTS 设置', 'tts.sub': '选择音色并转换当前素材。',
    'tts.target': '目标素材 — 将按以下设置转换。',
    'tts.preset': '音色组合预设', 'tts.speakerA': '说话人 A', 'tts.speakerB': '说话人 B',
    'tts.convert': '应用并转换', 'tts.reconvert': '重新合成',
    'tts.singleHint': '当前语料为单人对话，仅需配置 1 个音色；多余音色将按顺序使用。',
    'tts.statusReady': '语料已就绪 — 尚未合成。',
    'tts.statusExist': '已有音频 — 重新转换将替换现有音频。',
    'tr.regenerate': '重新生成', 'tr.refine': '编辑语料…', 'tr.editAudio': '编辑音频设置', 'tr.audioReady': '音频已就绪 — 可试听或发布。',
    'refine.title': '改进生成', 'refine.sub': '调整参数或添加指令，然后重新生成语料。',
    'refine.topic': '主题', 'refine.domain': '领域', 'refine.role': '角色', 'refine.scenario': '场景',
    'refine.difficulty': '词汇专业度', 'refine.difficultyDesc': '词汇难度范围，从 L1 生活化日常用语到 L5 学术级专业词汇。',
    'refine.length': '对话时长', 'refine.lengthDesc': '生成音频的大致时长，时间越长内容越充分。',
    'refine.depth': '句式复杂度', 'refine.depthDesc': '句法复杂程度，从 L1 简单短句到 L5 学术长难句。',
    'refine.secCore': '核心', 'refine.secScope': '深度与范围', 'refine.secDirectives': '指令', 'refine.secDir': '方向',
    'refine.inject': '改进指令', 'refine.injectPh': '例如：加入具体数值与测量数据、让对话更自然…',
    'refine.injectHint': '可选 — 注入生成提示。',
    'refine.dir': '生成方向', 'refine.dirDesc': '重写时希望朝哪个方向调整。',
    'refine.dirRephrase': '重写',
    'refine.dirExpand': '扩写',
    'refine.dirNarrow': '聚焦',
    'refine.dirAngle': '发散',
    'refine.dirRephraseDesc': '保持范围不变，仅调整措辞',
    'refine.dirExpandDesc': '增加更多技术细节',
    'refine.dirNarrowDesc': '聚焦单一侧面',
    'refine.dirAngleDesc': '发散到不同视角',
    'refine.tipDir': '重写：保持范围不变；扩写：增加更多细节与深度；聚焦：收敛到单一侧面；发散：换成不同视角重新组织。',
    'refine.apply': '改进并重新生成',
    'save.title': '保存', 'save.saved': '已保存', 'save.done': '已保存到我的素材 — ',
    'lib.rename': '重命名', 'lib.delete': '删除', 'lib.draft': '草稿', 'lib.unsynth': '未合成', 'lib.clearFilters': '清除筛选',
    'lib.renamed': '已重命名 — ', 'lib.deleted': '已删除 — ', 'lib.empty': '暂无素材', 'lib.nameExists': '已存在同名素材',
    'lib.emptyTitle': '暂无素材', 'lib.emptySub': '从真实场景生成一份双语听力素材，即刻开始练习。',
    'gen.tone': '语气与情绪',
    'tone.neutral': '中性专业', 'tone.urgent': '紧急 · 时间压力', 'tone.interview': '面试 · 高压问答',
    'tone.collaborative': '协作 · 冷静', 'tone.debate': '对抗性辩论', 'tone.mentoring': '讲解式指导',
    'tts.styleLabel': '情绪 / 风格',
    'tts.style.neutral': '中性', 'tts.style.cheerful': '欢快', 'tts.style.empathetic': '共情',
    'tts.style.serious': '严肃', 'tts.style.urgent': '急促', 'tts.style.whispering': '耳语',
    'pl.addTo': '播放列表', 'pl.title': '加入播放列表', 'pl.new': '新建播放列表…', 'pl.done': '完成',
    'pl.createPh': '播放列表名称…', 'pl.in': '收录于', 'pl.empty': '列表暂无素材', 'pl.exit': '退出播放列表视图', 'pl.all': '全部素材',
    'pl.created': '已创建播放列表 — ', 'pl.renamed': '已重命名播放列表 — ', 'pl.deleted': '已删除播放列表 — ', 'pl.added': '已加入 ', 'pl.removed': '已移出 ', 'pl.nameExists': '已存在同名播放列表',
    'del.title': '确认删除？', 'del.mTitle': '删除素材？', 'del.pTitle': '删除播放列表？',
    'del.cancel': '取消', 'del.delete': '删除',
    'del.materialText': '该素材将从素材库中永久删除，并从所有播放列表中移除。此操作无法撤销。',
    'del.materialInPl': '该素材将从素材库中永久删除，并从所有播放列表（含当前列表）中移除。此操作无法撤销。',
    'del.playlistText': '将删除该播放列表。列表内的素材会保留在素材库中。',
    'gen.stepC0': '解析参数并构建提示词', 'gen.stepC1': 'LLM 生成技术语料', 'gen.stepC2': '校验结构与技术锚定',
    'gen.stepA0': '逐句 TTS 语音合成', 'gen.stepA1': '拼接音频片段', 'gen.stepA2': '对齐句级时间轴',
    'gen.corpusLabel': '主题 — ', 'gen.audioLabel': 'TTS 合成 — ',
    'ph.corpus': '语料', 'ph.tts': 'TTS', 'ph.publish': '发布',
    'gen.publish': '发布',
    'pub.title': '发布素材', 'pub.sub': '为素材命名并保存到我的素材。',
    'pub.name': '文件名', 'pub.cancel': '取消', 'pub.ok': '发布', 'pub.done': '已发布 · '
  }
};
